name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node dependencies
        working-directory: SCE.Core/assets
        run: |
          npm install
      - name: Build dotnet
        run: dotnet build # /WarnAsError
